const translations = {
    es: {

        // Header Home
        _headerTitle: "Mis notas",
        _headerDropdownOption1: "Cambiar cuadricula",
        _headerDropdownOption2: "Configuración",

        // Header Note
        _headerNoteTitleNew: "Añadir nota",
        _headerNoteTitleEdit: "Editar nota",
        _headerNoteDropdownOption1: "Modo edición",
        _headerNoteDropdownOption2: "Modo lectura",
        _headerNoteDropdownOption3: "Eliminar nota",
        _headerNoteDropdownOption4: "Desbloquear nota",
        _headerNoteDropdownOption5: "Bloquear nota",
        _headerNoteDropdownOption6: "Configuración",
        _headerNoteDropdownOption7: "Añadir a favoritos",
        _headerNoteDropdownOption8: "Eliminar de favoritos",

        // Home
        _homeButton: "Añadir nota",
        _homeEmptyList: "No tienes ninguna nota creada",
        _elementsSelected: "elementos seleccionados",

        // Lista de idiomas
        _langListSpanish: "Español",
        _langListEnglish: "Inglés",
        _langListArabic: "Árabe",
        _langListGerman: "Alemán",
        _langListFrench: "Francés",
        _langListHindi: "Hindu",
        _langListIndonesian: "Indonesio",
        _langListPortuguese: "Portugués",
        _langListRussian: "Ruso",
        _langListPolish: "Polaco",
        _langListVietnamese: "Vietnamita",
        _langListTurkish: "Turco",
        _langListItalian: "Italiano",
        _langListFarsi: "Farsi",

        // Pantalla de settings
        _settingsApp: "Ajustes de la aplicación",
        _settingsLang: "Idioma de la aplicación",
        _settingsEditor: "Ajustes del editor",
        _settingsSave: "Guardado automático",
        _settingsTypo: "Tipografia",
        _settingsTypoWarning: "Al cambiar de tipografía se le enviará a la pantalla de inicio para cargar la nueva fuente",
        _settingsResetAll: "Reestablecer todo",
        _settingsRemoveAll: "Eliminar todas las notas",
        _settingsRemoveAllWarning: "¡CUIDADO! Al pulsar en el siguiente botón se eliminarán todas las notas guardadas",
        _settingsLineSpacing: "Espacio entre párrafos",
        _settingsLetterSpacing: "Espacio entre letras",
        _settingsWordSpacing: "Espacio entre palabras",


        // 05-09-2025: Faltaban las siguientes variables por traducir
        _settingTitle: "Configuración",
        _noteInputPlaceholder: "Escribe tu nota...",
        _toastNoteSaved: "Nota guardada",
        _toastTypoSaved: "Tipografía guardada",
        _toastAutoSave: "Guardado automatico",
        _toastActivated: "Activado",
        _toastDeactivated: "Desactivado",
        _toastAllNotesDeleted: "Se han eliminado todas las notas",
        _lockNoteTitle: "Introduce el código PIN",
        _lockInfo: "Esta nota está bloqueada, introduce el código PIN para poder acceder a ella",
        _lockError: "PIN incorrecto",
        _toastLineSpacingUpdated: "Se ha actualizado el interlineado de tus notas",
        _toastLetterSpacingUpdated: "Se ha actualizado el espacio entre letras de tus notas",
        _toastWordSpacingUpdated: "Se ha actualizado el espacio entre palabras de tus notas",

        // Modal de updates
        _updatesModalNews: "Novedades",
        _updatesModalV1_1: "¡Ahora puedes resaltar tus textos! 🖌️",
        _updatesModalV1_2: "Añadido un nuevo pincel de dibujo: Subrayador 🖍️",
        _updatesModalV1_3: "Se han mejorado las herramientas de dibujo 🔧",
        _updatesModalV1_4: "Personaliza el color de cada palabra 🎨",
        _updatesModalV1_5: "Edita el espacio entre párrafos, letras y palabras ↔️",
        _updatesModalV1_6: "😊 Esperamos que disfrutes de las novedades 😊",

    },
    en: { // Header Home
        "_headerTitle": "My Notes",
        "_headerDropdownOption1": "Change Grid",
        "_headerDropdownOption2": "Settings",
        // Header Note
        "_headerNoteTitleNew": "Add Note",
        "_headerNoteTitleEdit": "Edit Note",
        "_headerNoteDropdownOption1": "Edit Mode",
        "_headerNoteDropdownOption2": "Read Mode",
        "_headerNoteDropdownOption3": "Delete Note",
        "_headerNoteDropdownOption4": "Unlock Note",
        "_headerNoteDropdownOption5": "Lock Note",
        "_headerNoteDropdownOption6": "Settings",
        "_headerNoteDropdownOption7": "Add to Favorites",
        "_headerNoteDropdownOption8": "Remove from Favorites",
        // Home
        "_homeButton": "Add Note",
        "_homeEmptyList": "You have no notes created",
        "_elementsSelected": "selected items",
        // Lista de idiomas
        "_langListSpanish": "Spanish",
        "_langListEnglish": "English",
        "_langListArabic": "Arabic",
        "_langListGerman": "German",
        "_langListFrench": "French",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonesian",
        "_langListPortuguese": "Portuguese",
        "_langListRussian": "Russian",
        "_langListPolish": "Polish",
        "_langListVietnamese": "Vietnamese",
        "_langListTurkish": "Turkish",
        "_langListItalian": "Italian",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "App Settings",
        "_settingsLang": "App Language",
        "_settingsEditor": "Editor Settings",
        "_settingsSave": "Auto Save",
        "_settingsTypo": "Typography",
        "_settingsTypoWarning": "Changing the typography will redirect you to the home screen to load the new font",
        "_settingsResetAll": "Reset All",
        "_settingsRemoveAll": "Delete All Notes",
        "_settingsRemoveAllWarning": "WARNING! Pressing the button below will delete all saved notes",
        "_settingsLineSpacing": "Line Spacing",
        "_settingsLetterSpacing": "Letter Spacing",
        "_settingsWordSpacing": "Word Spacing",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Settings",
        "_noteInputPlaceholder": "Write your note...",
        "_toastNoteSaved": "Note Saved",
        "_toastTypoSaved": "Typography Saved",
        "_toastAutoSave": "Auto Saved",
        "_toastActivated": "Activated",
        "_toastDeactivated": "Deactivated",
        "_toastAllNotesDeleted": "All notes have been deleted",
        "_lockNoteTitle": "Enter PIN Code",
        "_lockInfo": "This note is locked, enter the PIN to access it",
        "_lockError": "Incorrect PIN",
        "_toastLineSpacingUpdated": "Your notes' line spacing has been updated",
        "_toastLetterSpacingUpdated": "Your notes' letter spacing has been updated",
        "_toastWordSpacingUpdated": "Your notes' word spacing has been updated",
        // Modal de updates
        "_updatesModalNews": "What's New",
        "_updatesModalV1_1": "You can now highlight your texts! 🖌️",
        "_updatesModalV1_2": "Added a new drawing brush: Highlighter 🖍️",
        "_updatesModalV1_3": "Drawing tools have been improved 🔧",
        "_updatesModalV1_4": "Customize the color of each word 🎨",
        "_updatesModalV1_5": "Edit spacing between paragraphs, letters, and words ↔️",
        "_updatesModalV1_6": "😊 We hope you enjoy the new features 😊"
    },
    fr: { // Header Home
        "_headerTitle": "Mes notes",
        "_headerDropdownOption1": "Changer la grille",
        "_headerDropdownOption2": "Paramètres",
        // Header Note
        "_headerNoteTitleNew": "Ajouter une note",
        "_headerNoteTitleEdit": "Modifier la note",
        "_headerNoteDropdownOption1": "Mode édition",
        "_headerNoteDropdownOption2": "Mode lecture",
        "_headerNoteDropdownOption3": "Supprimer la note",
        "_headerNoteDropdownOption4": "Déverrouiller la note",
        "_headerNoteDropdownOption5": "Verrouiller la note",
        "_headerNoteDropdownOption6": "Paramètres",
        "_headerNoteDropdownOption7": "Ajouter aux favoris",
        "_headerNoteDropdownOption8": "Retirer des favoris",
        // Home
        "_homeButton": "Ajouter une note",
        "_homeEmptyList": "Vous n'avez créé aucune note",
        "_elementsSelected": "éléments sélectionnés",
        // Lista de idiomas
        "_langListSpanish": "Espagnol",
        "_langListEnglish": "Anglais",
        "_langListArabic": "Arabe",
        "_langListGerman": "Allemand",
        "_langListFrench": "Français",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonésien",
        "_langListPortuguese": "Portugais",
        "_langListRussian": "Russe",
        "_langListPolish": "Polonais",
        "_langListVietnamese": "Vietnamien",
        "_langListTurkish": "Turc",
        "_langListItalian": "Italien",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "Paramètres de l'application",
        "_settingsLang": "Langue de l'application",
        "_settingsEditor": "Paramètres de l'éditeur",
        "_settingsSave": "Sauvegarde automatique",
        "_settingsTypo": "Typographie",
        "_settingsTypoWarning": "En changeant la typographie, vous serez redirigé vers l'écran d'accueil pour charger la nouvelle police",
        "_settingsResetAll": "Tout réinitialiser",
        "_settingsRemoveAll": "Supprimer toutes les notes",
        "_settingsRemoveAllWarning": "ATTENTION ! En appuyant sur le bouton ci-dessous, toutes les notes enregistrées seront supprimées",
        "_settingsLineSpacing": "Interligne",
        "_settingsLetterSpacing": "Espacement des lettres",
        "_settingsWordSpacing": "Espacement des mots",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Paramètres",
        "_noteInputPlaceholder": "Écrivez votre note...",
        "_toastNoteSaved": "Note enregistrée",
        "_toastTypoSaved": "Typographie enregistrée",
        "_toastAutoSave": "Enregistrement automatique",
        "_toastActivated": "Activé",
        "_toastDeactivated": "Désactivé",
        "_toastAllNotesDeleted": "Toutes les notes ont été supprimées",
        "_lockNoteTitle": "Entrez le code PIN",
        "_lockInfo": "Cette note est verrouillée, entrez le code PIN pour y accéder",
        "_lockError": "PIN incorrect",
        "_toastLineSpacingUpdated": "L'interligne de vos notes a été mis à jour",
        "_toastLetterSpacingUpdated": "L'espacement des lettres de vos notes a été mis à jour",
        "_toastWordSpacingUpdated": "L'espacement des mots de vos notes a été mis à jour",
        // Modal de updates
        "_updatesModalNews": "Nouveautés",
        "_updatesModalV1_1": "Vous pouvez maintenant surligner vos textes ! 🖌️",
        "_updatesModalV1_2": "Ajout d'un nouveau pinceau : Surligneur 🖍️",
        "_updatesModalV1_3": "Les outils de dessin ont été améliorés 🔧",
        "_updatesModalV1_4": "Personnalisez la couleur de chaque mot 🎨",
        "_updatesModalV1_5": "Modifiez l'espacement entre les paragraphes, les lettres et les mots ↔️",
        "_updatesModalV1_6": "😊 Nous espérons que vous apprécierez les nouveautés 😊"
    },
    de: { // Header Home
        "_headerTitle": "Meine Notizen",
        "_headerDropdownOption1": "Raster ändern",
        "_headerDropdownOption2": "Einstellungen",
        // Header Note
        "_headerNoteTitleNew": "Notiz hinzufügen",
        "_headerNoteTitleEdit": "Notiz bearbeiten",
        "_headerNoteDropdownOption1": "Bearbeitungsmodus",
        "_headerNoteDropdownOption2": "Lesemodus",
        "_headerNoteDropdownOption3": "Notiz löschen",
        "_headerNoteDropdownOption4": "Notiz entsperren",
        "_headerNoteDropdownOption5": "Notiz sperren",
        "_headerNoteDropdownOption6": "Einstellungen",
        "_headerNoteDropdownOption7": "Zu Favoriten hinzufügen",
        "_headerNoteDropdownOption8": "Aus Favoriten entfernen",
        // Home
        "_homeButton": "Notiz hinzufügen",
        "_homeEmptyList": "Du hast keine Notizen erstellt",
        "_elementsSelected": "ausgewählte Elemente",
        // Lista de idiomas
        "_langListSpanish": "Spanisch",
        "_langListEnglish": "Englisch",
        "_langListArabic": "Arabisch",
        "_langListGerman": "Deutsch",
        "_langListFrench": "Französisch",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonesisch",
        "_langListPortuguese": "Portugiesisch",
        "_langListRussian": "Russisch",
        "_langListPolish": "Polnisch",
        "_langListVietnamese": "Vietnamesisch",
        "_langListTurkish": "Türkisch",
        "_langListItalian": "Italienisch",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "App-Einstellungen",
        "_settingsLang": "App-Sprache",
        "_settingsEditor": "Editor-Einstellungen",
        "_settingsSave": "Automatisches Speichern",
        "_settingsTypo": "Typografie",
        "_settingsTypoWarning": "Beim Ändern der Typografie werden Sie zum Startbildschirm weitergeleitet, um die neue Schriftart zu laden",
        "_settingsResetAll": "Alles zurücksetzen",
        "_settingsRemoveAll": "Alle Notizen löschen",
        "_settingsRemoveAllWarning": "ACHTUNG! Durch Drücken der folgenden Taste werden alle gespeicherten Notizen gelöscht",
        "_settingsLineSpacing": "Zeilenabstand",
        "_settingsLetterSpacing": "Buchstabenabstand",
        "_settingsWordSpacing": "Wortabstand",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Einstellungen",
        "_noteInputPlaceholder": "Schreibe deine Notiz...",
        "_toastNoteSaved": "Notiz gespeichert",
        "_toastTypoSaved": "Typografie gespeichert",
        "_toastAutoSave": "Automatisch gespeichert",
        "_toastActivated": "Aktiviert",
        "_toastDeactivated": "Deaktiviert",
        "_toastAllNotesDeleted": "Alle Notizen wurden gelöscht",
        "_lockNoteTitle": "PIN eingeben",
        "_lockInfo": "Diese Notiz ist gesperrt, geben Sie den PIN ein, um darauf zuzugreifen",
        "_lockError": "Falscher PIN",
        "_toastLineSpacingUpdated": "Der Zeilenabstand deiner Notizen wurde aktualisiert",
        "_toastLetterSpacingUpdated": "Der Buchstabenabstand deiner Notizen wurde aktualisiert",
        "_toastWordSpacingUpdated": "Der Wortabstand deiner Notizen wurde aktualisiert",
        // Modal de updates
        "_updatesModalNews": "Neuigkeiten",
        "_updatesModalV1_1": "Du kannst jetzt deine Texte hervorheben! 🖌️",
        "_updatesModalV1_2": "Neuer Zeichenpinsel hinzugefügt: Textmarker 🖍️",
        "_updatesModalV1_3": "Zeichenwerkzeuge wurden verbessert 🔧",
        "_updatesModalV1_4": "Passe die Farbe jedes Wortes an 🎨",
        "_updatesModalV1_5": "Bearbeite den Abstand zwischen Absätzen, Buchstaben und Wörtern ↔️",
        "_updatesModalV1_6": "😊 Wir hoffen, du genießt die neuen Funktionen 😊"
    },
    ar: { // Header Home
        "_headerTitle": "ملاحظاتي",
        "_headerDropdownOption1": "تغيير الشبكة",
        "_headerDropdownOption2": "الإعدادات",
        // Header Note
        "_headerNoteTitleNew": "إضافة ملاحظة",
        "_headerNoteTitleEdit": "تعديل الملاحظة",
        "_headerNoteDropdownOption1": "وضع التحرير",
        "_headerNoteDropdownOption2": "وضع القراءة",
        "_headerNoteDropdownOption3": "حذف الملاحظة",
        "_headerNoteDropdownOption4": "إلغاء قفل الملاحظة",
        "_headerNoteDropdownOption5": "قفل الملاحظة",
        "_headerNoteDropdownOption6": "الإعدادات",
        "_headerNoteDropdownOption7": "إضافة إلى المفضلة",
        "_headerNoteDropdownOption8": "إزالة من المفضلة",
        // Home
        "_homeButton": "إضافة ملاحظة",
        "_homeEmptyList": "ليس لديك أي ملاحظات",
        "_elementsSelected": "عناصر محددة",
        // Lista de idiomas
        "_langListSpanish": "الإسبانية",
        "_langListEnglish": "الإنجليزية",
        "_langListArabic": "العربية",
        "_langListGerman": "الألمانية",
        "_langListFrench": "الفرنسية",
        "_langListHindi": "الهندية",
        "_langListIndonesian": "الإندونيسية",
        "_langListPortuguese": "البرتغالية",
        "_langListRussian": "الروسية",
        "_langListPolish": "البولندية",
        "_langListVietnamese": "الفيتنامية",
        "_langListTurkish": "التركية",
        "_langListItalian": "الإيطالية",
        "_langListFarsi": "الفارسية",
        // Pantalla de settings
        "_settingsApp": "إعدادات التطبيق",
        "_settingsLang": "لغة التطبيق",
        "_settingsEditor": "إعدادات المحرر",
        "_settingsSave": "الحفظ التلقائي",
        "_settingsTypo": "الخط",
        "_settingsTypoWarning": "سيتم نقلك إلى الشاشة الرئيسية لتحميل الخط الجديد عند تغييره",
        "_settingsResetAll": "إعادة تعيين الكل",
        "_settingsRemoveAll": "حذف جميع الملاحظات",
        "_settingsRemoveAllWarning": "تحذير! سيؤدي الضغط على الزر أدناه إلى حذف جميع الملاحظات المحفوظة",
        "_settingsLineSpacing": "تباعد الأسطر",
        "_settingsLetterSpacing": "تباعد الحروف",
        "_settingsWordSpacing": "تباعد الكلمات",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "الإعدادات",
        "_noteInputPlaceholder": "اكتب ملاحظتك...",
        "_toastNoteSaved": "تم حفظ الملاحظة",
        "_toastTypoSaved": "تم حفظ الخط",
        "_toastAutoSave": "تم الحفظ التلقائي",
        "_toastActivated": "تم التفعيل",
        "_toastDeactivated": "تم التعطيل",
        "_toastAllNotesDeleted": "تم حذف جميع الملاحظات",
        "_lockNoteTitle": "أدخل رمز PIN",
        "_lockInfo": "هذه الملاحظة مقفلة، أدخل رمز PIN للوصول إليها",
        "_lockError": "رمز PIN غير صحيح",
        "_toastLineSpacingUpdated": "تم تحديث تباعد الأسطر في ملاحظاتك",
        "_toastLetterSpacingUpdated": "تم تحديث تباعد الحروف في ملاحظاتك",
        "_toastWordSpacingUpdated": "تم تحديث تباعد الكلمات في ملاحظاتك",
        // Modal de updates
        "_updatesModalNews": "جديد",
        "_updatesModalV1_1": "يمكنك الآن تمييز النصوص! 🖌️",
        "_updatesModalV1_2": "تمت إضافة فرشاة جديدة: قلم التمييز 🖍️",
        "_updatesModalV1_3": "تم تحسين أدوات الرسم 🔧",
        "_updatesModalV1_4": "خصص لون كل كلمة 🎨",
        "_updatesModalV1_5": "قم بتحرير المسافة بين الفقرات والحروف والكلمات ↔️",
        "_updatesModalV1_6": "😊 نأمل أن تستمتع بالتحديثات 😊"
    },
    hi: { // Header Home
        "_headerTitle": "मेरे नोट्स",
        "_headerDropdownOption1": "ग्रिड बदलें",
        "_headerDropdownOption2": "सेटिंग्स",
        // Header Note
        "_headerNoteTitleNew": "नोट जोड़ें",
        "_headerNoteTitleEdit": "नोट संपादित करें",
        "_headerNoteDropdownOption1": "संपादन मोड",
        "_headerNoteDropdownOption2": "पढ़ने का मोड",
        "_headerNoteDropdownOption3": "नोट हटाएं",
        "_headerNoteDropdownOption4": "नोट अनलॉक करें",
        "_headerNoteDropdownOption5": "नोट लॉक करें",
        "_headerNoteDropdownOption6": "सेटिंग्स",
        "_headerNoteDropdownOption7": "पसंदीदा में जोड़ें",
        "_headerNoteDropdownOption8": "पसंदीदा से हटाएं",
        // Home
        "_homeButton": "नोट जोड़ें",
        "_homeEmptyList": "आपके पास कोई नोट नहीं है",
        "_elementsSelected": "चयनित आइटम",
        // Lista de idiomas
        "_langListSpanish": "स्पेनिश",
        "_langListEnglish": "अंग्रेज़ी",
        "_langListArabic": "अरबी",
        "_langListGerman": "जर्मन",
        "_langListFrench": "फ़्रेंच",
        "_langListHindi": "हिंदी",
        "_langListIndonesian": "इंडोनेशियाई",
        "_langListPortuguese": "पुर्तगाली",
        "_langListRussian": "रूसी",
        "_langListPolish": "पोलिश",
        "_langListVietnamese": "वियतनामी",
        "_langListTurkish": "तुर्की",
        "_langListItalian": "इतालवी",
        "_langListFarsi": "फ़ारसी",
        // Pantalla de settings
        "_settingsApp": "ऐप सेटिंग्स",
        "_settingsLang": "ऐप भाषा",
        "_settingsEditor": "संपादक सेटिंग्स",
        "_settingsSave": "स्वचालित सहेजना",
        "_settingsTypo": "टाइपोग्राफी",
        "_settingsTypoWarning": "टाइपोग्राफी बदलने पर आपको नई फ़ॉन्ट लोड करने के लिए होम स्क्रीन पर भेजा जाएगा",
        "_settingsResetAll": "सब रीसेट करें",
        "_settingsRemoveAll": "सभी नोट हटाएं",
        "_settingsRemoveAllWarning": "चेतावनी! नीचे दिए गए बटन पर क्लिक करने से सभी सहेजे गए नोट हटा दिए जाएंगे",
        "_settingsLineSpacing": "पंक्ति अंतर",
        "_settingsLetterSpacing": "अक्षर अंतर",
        "_settingsWordSpacing": "शब्द अंतर",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "सेटिंग्स",
        "_noteInputPlaceholder": "अपना नोट लिखें...",
        "_toastNoteSaved": "नोट सहेजा गया",
        "_toastTypoSaved": "टाइपोग्राफी सहेजी गई",
        "_toastAutoSave": "स्वचालित सहेजना",
        "_toastActivated": "सक्रिय किया गया",
        "_toastDeactivated": "निष्क्रिय किया गया",
        "_toastAllNotesDeleted": "सभी नोट हटाए गए",
        "_lockNoteTitle": "PIN कोड दर्ज करें",
        "_lockInfo": "यह नोट लॉक है, इसे एक्सेस करने के लिए PIN दर्ज करें",
        "_lockError": "गलत PIN",
        "_toastLineSpacingUpdated": "आपके नोट्स का पंक्ति अंतर अपडेट किया गया है",
        "_toastLetterSpacingUpdated": "आपके नोट्स का अक्षर अंतर अपडेट किया गया है",
        "_toastWordSpacingUpdated": "आपके नोट्स का शब्द अंतर अपडेट किया गया है",
        // Modal de updates
        "_updatesModalNews": "नए फीचर्स",
        "_updatesModalV1_1": "अब आप अपने टेक्स्ट को हाइलाइट कर सकते हैं! 🖌️",
        "_updatesModalV1_2": "नया ब्रश जोड़ा गया: हाइलाइटर 🖍️",
        "_updatesModalV1_3": "ड्रॉइंग टूल्स को बेहतर बनाया गया है 🔧",
        "_updatesModalV1_4": "हर शब्द का रंग कस्टमाइज़ करें 🎨",
        "_updatesModalV1_5": "पैराग्राफ, अक्षर और शब्द के बीच की स्पेस एडिट करें ↔️",
        "_updatesModalV1_6": "😊 हमें उम्मीद है कि आपको नए फीचर्स पसंद आएंगे 😊"
    },
    vi: { // Header Home
        "_headerTitle": "Ghi chú của tôi",
        "_headerDropdownOption1": "Thay đổi lưới",
        "_headerDropdownOption2": "Cài đặt",
        // Header Note
        "_headerNoteTitleNew": "Thêm ghi chú",
        "_headerNoteTitleEdit": "Chỉnh sửa ghi chú",
        "_headerNoteDropdownOption1": "Chế độ chỉnh sửa",
        "_headerNoteDropdownOption2": "Chế độ đọc",
        "_headerNoteDropdownOption3": "Xóa ghi chú",
        "_headerNoteDropdownOption4": "Mở khóa ghi chú",
        "_headerNoteDropdownOption5": "Khóa ghi chú",
        "_headerNoteDropdownOption6": "Cài đặt",
        "_headerNoteDropdownOption7": "Thêm vào yêu thích",
        "_headerNoteDropdownOption8": "Xóa khỏi yêu thích",
        // Home
        "_homeButton": "Thêm ghi chú",
        "_homeEmptyList": "Bạn chưa tạo ghi chú nào",
        "_elementsSelected": "mục đã chọn",
        // Lista de idiomas
        "_langListSpanish": "Tiếng Tây Ban Nha",
        "_langListEnglish": "Tiếng Anh",
        "_langListArabic": "Tiếng Ả Rập",
        "_langListGerman": "Tiếng Đức",
        "_langListFrench": "Tiếng Pháp",
        "_langListHindi": "Tiếng Hindi",
        "_langListIndonesian": "Tiếng Indonesia",
        "_langListPortuguese": "Tiếng Bồ Đào Nha",
        "_langListRussian": "Tiếng Nga",
        "_langListPolish": "Tiếng Ba Lan",
        "_langListVietnamese": "Tiếng Việt",
        "_langListTurkish": "Tiếng Thổ Nhĩ Kỳ",
        "_langListItalian": "Tiếng Ý",
        "_langListFarsi": "Tiếng Ba Tư",
        // Pantalla de settings
        "_settingsApp": "Cài đặt ứng dụng",
        "_settingsLang": "Ngôn ngữ ứng dụng",
        "_settingsEditor": "Cài đặt trình chỉnh sửa",
        "_settingsSave": "Tự động lưu",
        "_settingsTypo": "Phông chữ",
        "_settingsTypoWarning": "Thay đổi phông chữ sẽ đưa bạn về màn hình chính để tải phông mới",
        "_settingsResetAll": "Đặt lại tất cả",
        "_settingsRemoveAll": "Xóa tất cả ghi chú",
        "_settingsRemoveAllWarning": "CẢNH BÁO! Nhấn nút bên dưới sẽ xóa tất cả ghi chú đã lưu",
        "_settingsLineSpacing": "Khoảng cách dòng",
        "_settingsLetterSpacing": "Khoảng cách chữ",
        "_settingsWordSpacing": "Khoảng cách từ",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Cài đặt",
        "_noteInputPlaceholder": "Viết ghi chú của bạn...",
        "_toastNoteSaved": "Đã lưu ghi chú",
        "_toastTypoSaved": "Đã lưu phông chữ",
        "_toastAutoSave": "Đã lưu tự động",
        "_toastActivated": "Đã kích hoạt",
        "_toastDeactivated": "Đã tắt",
        "_toastAllNotesDeleted": "Đã xóa tất cả ghi chú",
        "_lockNoteTitle": "Nhập mã PIN",
        "_lockInfo": "Ghi chú này đã bị khóa, nhập mã PIN để truy cập",
        "_lockError": "Mã PIN không đúng",
        "_toastLineSpacingUpdated": "Khoảng cách dòng trong ghi chú của bạn đã được cập nhật",
        "_toastLetterSpacingUpdated": "Khoảng cách chữ trong ghi chú của bạn đã được cập nhật",
        "_toastWordSpacingUpdated": "Khoảng cách từ trong ghi chú của bạn đã được cập nhật",
        // Modal de updates
        "_updatesModalNews": "Có gì mới",
        "_updatesModalV1_1": "Bây giờ bạn có thể tô sáng văn bản của mình! 🖌️",
        "_updatesModalV1_2": "Đã thêm bút vẽ mới: Bút đánh dấu 🖍️",
        "_updatesModalV1_3": "Các công cụ vẽ đã được cải thiện 🔧",
        "_updatesModalV1_4": "Tùy chỉnh màu sắc của từng từ 🎨",
        "_updatesModalV1_5": "Chỉnh sửa khoảng cách giữa đoạn, chữ và từ ↔️",
        "_updatesModalV1_6": "😊 Chúng tôi hy vọng bạn thích các tính năng mới 😊"
    },
    pl: { // Header Home
        "_headerTitle": "Moje notatki",
        "_headerDropdownOption1": "Zmień siatkę",
        "_headerDropdownOption2": "Ustawienia",
        // Header Note
        "_headerNoteTitleNew": "Dodaj notatkę",
        "_headerNoteTitleEdit": "Edytuj notatkę",
        "_headerNoteDropdownOption1": "Tryb edycji",
        "_headerNoteDropdownOption2": "Tryb czytania",
        "_headerNoteDropdownOption3": "Usuń notatkę",
        "_headerNoteDropdownOption4": "Odblokuj notatkę",
        "_headerNoteDropdownOption5": "Zablokuj notatkę",
        "_headerNoteDropdownOption6": "Ustawienia",
        "_headerNoteDropdownOption7": "Dodaj do ulubionych",
        "_headerNoteDropdownOption8": "Usuń z ulubionych",
        // Home
        "_homeButton": "Dodaj notatkę",
        "_homeEmptyList": "Nie masz żadnych notatek",
        "_elementsSelected": "wybrane elementy",
        // Lista de idiomas
        "_langListSpanish": "Hiszpański",
        "_langListEnglish": "Angielski",
        "_langListArabic": "Arabski",
        "_langListGerman": "Niemiecki",
        "_langListFrench": "Francuski",
        "_langListHindi": "Hinduski",
        "_langListIndonesian": "Indonezyjski",
        "_langListPortuguese": "Portugalski",
        "_langListRussian": "Rosyjski",
        "_langListPolish": "Polski",
        "_langListVietnamese": "Wietnamski",
        "_langListTurkish": "Turecki",
        "_langListItalian": "Włoski",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "Ustawienia aplikacji",
        "_settingsLang": "Język aplikacji",
        "_settingsEditor": "Ustawienia edytora",
        "_settingsSave": "Automatyczne zapisywanie",
        "_settingsTypo": "Typografia",
        "_settingsTypoWarning": "Zmiana typografii przeniesie Cię na ekran główny w celu załadowania nowej czcionki",
        "_settingsResetAll": "Zresetuj wszystko",
        "_settingsRemoveAll": "Usuń wszystkie notatki",
        "_settingsRemoveAllWarning": "UWAGA! Naciśnięcie poniższego przycisku usunie wszystkie zapisane notatki",
        "_settingsLineSpacing": "Odstępy między liniami",
        "_settingsLetterSpacing": "Odstępy między literami",
        "_settingsWordSpacing": "Odstępy między słowami",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Ustawienia",
        "_noteInputPlaceholder": "Napisz swoją notatkę...",
        "_toastNoteSaved": "Notatka zapisana",
        "_toastTypoSaved": "Typografia zapisana",
        "_toastAutoSave": "Zapisano automatycznie",
        "_toastActivated": "Aktywowano",
        "_toastDeactivated": "Dezaktywowano",
        "_toastAllNotesDeleted": "Wszystkie notatki zostały usunięte",
        "_lockNoteTitle": "Wprowadź kod PIN",
        "_lockInfo": "Ta notatka jest zablokowana, wprowadź kod PIN, aby uzyskać dostęp",
        "_lockError": "Nieprawidłowy PIN",
        "_toastLineSpacingUpdated": "Zaktualizowano odstępy między liniami w Twoich notatkach",
        "_toastLetterSpacingUpdated": "Zaktualizowano odstępy między literami w Twoich notatkach",
        "_toastWordSpacingUpdated": "Zaktualizowano odstępy między słowami w Twoich notatkach",
        // Modal de updates
        "_updatesModalNews": "Nowości",
        "_updatesModalV1_1": "Teraz możesz podkreślać swoje teksty! 🖌️",
        "_updatesModalV1_2": "Dodano nowy pędzel: Zakreślacz 🖍️",
        "_updatesModalV1_3": "Ulepszono narzędzia do rysowania 🔧",
        "_updatesModalV1_4": "Dostosuj kolor każdego słowa 🎨",
        "_updatesModalV1_5": "Edytuj odstępy między akapitami, literami i słowami ↔️",
        "_updatesModalV1_6": "😊 Mamy nadzieję, że spodoba Ci się nowości 😊"
    },
    pt: { // Header Home
        "_headerTitle": "Minhas Notas",
        "_headerDropdownOption1": "Mudar Grade",
        "_headerDropdownOption2": "Configurações",
        // Header Note
        "_headerNoteTitleNew": "Adicionar Nota",
        "_headerNoteTitleEdit": "Editar Nota",
        "_headerNoteDropdownOption1": "Modo de Edição",
        "_headerNoteDropdownOption2": "Modo de Leitura",
        "_headerNoteDropdownOption3": "Excluir Nota",
        "_headerNoteDropdownOption4": "Desbloquear Nota",
        "_headerNoteDropdownOption5": "Bloquear Nota",
        "_headerNoteDropdownOption6": "Configurações",
        "_headerNoteDropdownOption7": "Adicionar aos Favoritos",
        "_headerNoteDropdownOption8": "Remover dos Favoritos",
        // Home
        "_homeButton": "Adicionar Nota",
        "_homeEmptyList": "Você não tem nenhuma nota",
        "_elementsSelected": "itens selecionados",
        // Lista de idiomas
        "_langListSpanish": "Espanhol",
        "_langListEnglish": "Inglês",
        "_langListArabic": "Árabe",
        "_langListGerman": "Alemão",
        "_langListFrench": "Francês",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonésio",
        "_langListPortuguese": "Português",
        "_langListRussian": "Russo",
        "_langListPolish": "Polonês",
        "_langListVietnamese": "Vietnamita",
        "_langListTurkish": "Turco",
        "_langListItalian": "Italiano",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "Configurações do Aplicativo",
        "_settingsLang": "Idioma do Aplicativo",
        "_settingsEditor": "Configurações do Editor",
        "_settingsSave": "Salvamento Automático",
        "_settingsTypo": "Tipografia",
        "_settingsTypoWarning": "Ao alterar a tipografia, você será redirecionado para a tela inicial para carregar a nova fonte",
        "_settingsResetAll": "Redefinir Tudo",
        "_settingsRemoveAll": "Excluir Todas as Notas",
        "_settingsRemoveAllWarning": "ATENÇÃO! Pressionar o botão abaixo excluirá todas as notas salvas",
        "_settingsLineSpacing": "Espaçamento entre Linhas",
        "_settingsLetterSpacing": "Espaçamento entre Letras",
        "_settingsWordSpacing": "Espaçamento entre Palavras",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Configurações",
        "_noteInputPlaceholder": "Escreva sua nota...",
        "_toastNoteSaved": "Nota Salva",
        "_toastTypoSaved": "Tipografia Salva",
        "_toastAutoSave": "Salvo Automaticamente",
        "_toastActivated": "Ativado",
        "_toastDeactivated": "Desativado",
        "_toastAllNotesDeleted": "Todas as notas foram excluídas",
        "_lockNoteTitle": "Digite o Código PIN",
        "_lockInfo": "Esta nota está bloqueada, digite o PIN para acessá-la",
        "_lockError": "PIN incorreto",
        "_toastLineSpacingUpdated": "O espaçamento entre linhas foi atualizado",
        "_toastLetterSpacingUpdated": "O espaçamento entre letras foi atualizado",
        "_toastWordSpacingUpdated": "O espaçamento entre palavras foi atualizado",
        // Modal de updates
        "_updatesModalNews": "Novidades",
        "_updatesModalV1_1": "Agora você pode destacar seus textos! 🖌️",
        "_updatesModalV1_2": "Novo pincel adicionado: Marcador 🖍️",
        "_updatesModalV1_3": "Ferramentas de desenho melhoradas 🔧",
        "_updatesModalV1_4": "Personalize a cor de cada palavra 🎨",
        "_updatesModalV1_5": "Edite o espaçamento entre parágrafos, letras e palavras ↔️",
        "_updatesModalV1_6": "😊 Esperamos que você aproveite as novidades 😊"
    },
    tr: { // Header Home
        "_headerTitle": "Notlarım",
        "_headerDropdownOption1": "Izgara Değiştir",
        "_headerDropdownOption2": "Ayarlar",
        // Header Note
        "_headerNoteTitleNew": "Not Ekle",
        "_headerNoteTitleEdit": "Notu Düzenle",
        "_headerNoteDropdownOption1": "Düzenleme Modu",
        "_headerNoteDropdownOption2": "Okuma Modu",
        "_headerNoteDropdownOption3": "Notu Sil",
        "_headerNoteDropdownOption4": "Notu Kilidi Aç",
        "_headerNoteDropdownOption5": "Notu Kilitle",
        "_headerNoteDropdownOption6": "Ayarlar",
        "_headerNoteDropdownOption7": "Favorilere Ekle",
        "_headerNoteDropdownOption8": "Favorilerden Kaldır",
        // Home
        "_homeButton": "Not Ekle",
        "_homeEmptyList": "Hiç notunuz yok",
        "_elementsSelected": "seçilen öğeler",
        // Lista de idiomas
        "_langListSpanish": "İspanyolca",
        "_langListEnglish": "İngilizce",
        "_langListArabic": "Arapça",
        "_langListGerman": "Almanca",
        "_langListFrench": "Fransızca",
        "_langListHindi": "Hintçe",
        "_langListIndonesian": "Endonezce",
        "_langListPortuguese": "Portekizce",
        "_langListRussian": "Rusça",
        "_langListPolish": "Lehçe",
        "_langListVietnamese": "Vietnamca",
        "_langListTurkish": "Türkçe",
        "_langListItalian": "İtalyanca",
        "_langListFarsi": "Farsça",
        // Pantalla de settings
        "_settingsApp": "Uygulama Ayarları",
        "_settingsLang": "Uygulama Dili",
        "_settingsEditor": "Düzenleyici Ayarları",
        "_settingsSave": "Otomatik Kaydetme",
        "_settingsTypo": "Tipografi",
        "_settingsTypoWarning": "Tipografi değiştirildiğinde yeni fontu yüklemek için ana ekrana yönlendirileceksiniz",
        "_settingsResetAll": "Hepsini Sıfırla",
        "_settingsRemoveAll": "Tüm Notları Sil",
        "_settingsRemoveAllWarning": "DİKKAT! Aşağıdaki düğmeye basıldığında tüm notlar silinecek",
        "_settingsLineSpacing": "Satır Aralığı",
        "_settingsLetterSpacing": "Harf Aralığı",
        "_settingsWordSpacing": "Kelime Aralığı",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Ayarlar",
        "_noteInputPlaceholder": "Notunuzu yazın...",
        "_toastNoteSaved": "Not Kaydedildi",
        "_toastTypoSaved": "Tipografi Kaydedildi",
        "_toastAutoSave": "Otomatik Kaydedildi",
        "_toastActivated": "Aktif Edildi",
        "_toastDeactivated": "Devre Dışı Bırakıldı",
        "_toastAllNotesDeleted": "Tüm notlar silindi",
        "_lockNoteTitle": "PIN Kodunu Girin",
        "_lockInfo": "Bu not kilitli, erişim için PIN kodunu girin",
        "_lockError": "Hatalı PIN",
        "_toastLineSpacingUpdated": "Satır aralığı güncellendi",
        "_toastLetterSpacingUpdated": "Harf aralığı güncellendi",
        "_toastWordSpacingUpdated": "Kelime aralığı güncellendi",
        // Modal de updates
        "_updatesModalNews": "Yenilikler",
        "_updatesModalV1_1": "Artık metinlerinizi vurgulayabilirsiniz! 🖌️",
        "_updatesModalV1_2": "Yeni fırça eklendi: Fosforlu Kalem 🖍️",
        "_updatesModalV1_3": "Çizim araçları geliştirildi 🔧",
        "_updatesModalV1_4": "Her kelimenin rengini özelleştirin 🎨",
        "_updatesModalV1_5": "Paragraflar, harfler ve kelimeler arasındaki boşluğu düzenleyin ↔️",
        "_updatesModalV1_6": "😊 Yeniliklerin keyfini çıkarın 😊"
    },
    id: { // Header Home
        "_headerTitle": "Catatan Saya",
        "_headerDropdownOption1": "Ubah Kisi",
        "_headerDropdownOption2": "Pengaturan",
        // Header Note
        "_headerNoteTitleNew": "Tambah Catatan",
        "_headerNoteTitleEdit": "Edit Catatan",
        "_headerNoteDropdownOption1": "Mode Edit",
        "_headerNoteDropdownOption2": "Mode Baca",
        "_headerNoteDropdownOption3": "Hapus Catatan",
        "_headerNoteDropdownOption4": "Buka Kunci Catatan",
        "_headerNoteDropdownOption5": "Kunci Catatan",
        "_headerNoteDropdownOption6": "Pengaturan",
        "_headerNoteDropdownOption7": "Tambahkan ke Favorit",
        "_headerNoteDropdownOption8": "Hapus dari Favorit",
        // Home
        "_homeButton": "Tambah Catatan",
        "_homeEmptyList": "Anda tidak memiliki catatan",
        "_elementsSelected": "item dipilih",
        // Lista de idiomas
        "_langListSpanish": "Spanyol",
        "_langListEnglish": "Inggris",
        "_langListArabic": "Arab",
        "_langListGerman": "Jerman",
        "_langListFrench": "Prancis",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonesia",
        "_langListPortuguese": "Portugis",
        "_langListRussian": "Rusia",
        "_langListPolish": "Polandia",
        "_langListVietnamese": "Vietnam",
        "_langListTurkish": "Turki",
        "_langListItalian": "Italia",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "Pengaturan Aplikasi",
        "_settingsLang": "Bahasa Aplikasi",
        "_settingsEditor": "Pengaturan Editor",
        "_settingsSave": "Simpan Otomatis",
        "_settingsTypo": "Tipografi",
        "_settingsTypoWarning": "Mengubah tipografi akan mengarahkan Anda ke layar utama untuk memuat font baru",
        "_settingsResetAll": "Atur Ulang Semua",
        "_settingsRemoveAll": "Hapus Semua Catatan",
        "_settingsRemoveAllWarning": "PERINGATAN! Menekan tombol di bawah ini akan menghapus semua catatan yang disimpan",
        "_settingsLineSpacing": "Jarak Baris",
        "_settingsLetterSpacing": "Jarak Huruf",
        "_settingsWordSpacing": "Jarak Kata",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Pengaturan",
        "_noteInputPlaceholder": "Tulis catatan Anda...",
        "_toastNoteSaved": "Catatan Disimpan",
        "_toastTypoSaved": "Tipografi Disimpan",
        "_toastAutoSave": "Disimpan Otomatis",
        "_toastActivated": "Diaktifkan",
        "_toastDeactivated": "Dinonaktifkan",
        "_toastAllNotesDeleted": "Semua catatan telah dihapus",
        "_lockNoteTitle": "Masukkan Kode PIN",
        "_lockInfo": "Catatan ini terkunci, masukkan PIN untuk mengaksesnya",
        "_lockError": "PIN salah",
        "_toastLineSpacingUpdated": "Jarak baris pada catatan Anda telah diperbarui",
        "_toastLetterSpacingUpdated": "Jarak huruf pada catatan Anda telah diperbarui",
        "_toastWordSpacingUpdated": "Jarak kata pada catatan Anda telah diperbarui",
        // Modal de updates
        "_updatesModalNews": "Berita",
        "_updatesModalV1_1": "Sekarang Anda dapat menyoroti teks Anda! 🖌️",
        "_updatesModalV1_2": "Kuas baru ditambahkan: Stabilo 🖍️",
        "_updatesModalV1_3": "Alat menggambar telah ditingkatkan 🔧",
        "_updatesModalV1_4": "Sesuaikan warna setiap kata 🎨",
        "_updatesModalV1_5": "Edit jarak antar paragraf, huruf, dan kata ↔️",
        "_updatesModalV1_6": "😊 Semoga Anda menikmati fitur baru 😊"
    },
    ru: { // Header Home
        "_headerTitle": "Мои заметки",
        "_headerDropdownOption1": "Изменить сетку",
        "_headerDropdownOption2": "Настройки",
        // Header Note
        "_headerNoteTitleNew": "Добавить заметку",
        "_headerNoteTitleEdit": "Редактировать заметку",
        "_headerNoteDropdownOption1": "Режим редактирования",
        "_headerNoteDropdownOption2": "Режим чтения",
        "_headerNoteDropdownOption3": "Удалить заметку",
        "_headerNoteDropdownOption4": "Разблокировать заметку",
        "_headerNoteDropdownOption5": "Заблокировать заметку",
        "_headerNoteDropdownOption6": "Настройки",
        "_headerNoteDropdownOption7": "Добавить в избранное",
        "_headerNoteDropdownOption8": "Удалить из избранного",
        // Home
        "_homeButton": "Добавить заметку",
        "_homeEmptyList": "У вас нет заметок",
        "_elementsSelected": "выбранные элементы",
        // Lista de idiomas
        "_langListSpanish": "Испанский",
        "_langListEnglish": "Английский",
        "_langListArabic": "Арабский",
        "_langListGerman": "Немецкий",
        "_langListFrench": "Французский",
        "_langListHindi": "Хинди",
        "_langListIndonesian": "Индонезийский",
        "_langListPortuguese": "Португальский",
        "_langListRussian": "Русский",
        "_langListPolish": "Польский",
        "_langListVietnamese": "Вьетнамский",
        "_langListTurkish": "Турецкий",
        "_langListItalian": "Итальянский",
        "_langListFarsi": "Фарси",
        // Pantalla de settings
        "_settingsApp": "Настройки приложения",
        "_settingsLang": "Язык приложения",
        "_settingsEditor": "Настройки редактора",
        "_settingsSave": "Автосохранение",
        "_settingsTypo": "Типография",
        "_settingsTypoWarning": "Изменение шрифта вернет вас на главный экран для загрузки нового шрифта",
        "_settingsResetAll": "Сбросить все",
        "_settingsRemoveAll": "Удалить все заметки",
        "_settingsRemoveAllWarning": "ВНИМАНИЕ! Нажатие на кнопку ниже удалит все сохраненные заметки",
        "_settingsLineSpacing": "Межстрочный интервал",
        "_settingsLetterSpacing": "Интервал между буквами",
        "_settingsWordSpacing": "Интервал между словами",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Настройки",
        "_noteInputPlaceholder": "Напишите вашу заметку...",
        "_toastNoteSaved": "Заметка сохранена",
        "_toastTypoSaved": "Шрифт сохранен",
        "_toastAutoSave": "Автоматически сохранено",
        "_toastActivated": "Активировано",
        "_toastDeactivated": "Деактивировано",
        "_toastAllNotesDeleted": "Все заметки удалены",
        "_lockNoteTitle": "Введите PIN-код",
        "_lockInfo": "Эта заметка заблокирована, введите PIN для доступа",
        "_lockError": "Неверный PIN",
        "_toastLineSpacingUpdated": "Межстрочный интервал обновлен",
        "_toastLetterSpacingUpdated": "Интервал между буквами обновлен",
        "_toastWordSpacingUpdated": "Интервал между словами обновлен",
        // Modal de updates
        "_updatesModalNews": "Новости",
        "_updatesModalV1_1": "Теперь вы можете выделять текст! 🖌️",
        "_updatesModalV1_2": "Добавлена новая кисть: Маркер 🖍️",
        "_updatesModalV1_3": "Улучшены инструменты для рисования 🔧",
        "_updatesModalV1_4": "Настройте цвет каждого слова 🎨",
        "_updatesModalV1_5": "Редактируйте интервалы между абзацами, буквами и словами ↔️",
        "_updatesModalV1_6": "😊 Надеемся, вам понравятся обновления 😊"
    },
    it: { // Header Home
        "_headerTitle": "Le mie note",
        "_headerDropdownOption1": "Cambia griglia",
        "_headerDropdownOption2": "Impostazioni",
        // Header Note
        "_headerNoteTitleNew": "Aggiungi nota",
        "_headerNoteTitleEdit": "Modifica nota",
        "_headerNoteDropdownOption1": "Modalità modifica",
        "_headerNoteDropdownOption2": "Modalità lettura",
        "_headerNoteDropdownOption3": "Elimina nota",
        "_headerNoteDropdownOption4": "Sblocca nota",
        "_headerNoteDropdownOption5": "Blocca nota",
        "_headerNoteDropdownOption6": "Impostazioni",
        "_headerNoteDropdownOption7": "Aggiungi ai preferiti",
        "_headerNoteDropdownOption8": "Rimuovi dai preferiti",
        // Home
        "_homeButton": "Aggiungi nota",
        "_homeEmptyList": "Non hai alcuna nota",
        "_elementsSelected": "elementi selezionati",
        // Lista de idiomas
        "_langListSpanish": "Spagnolo",
        "_langListEnglish": "Inglese",
        "_langListArabic": "Arabo",
        "_langListGerman": "Tedesco",
        "_langListFrench": "Francese",
        "_langListHindi": "Hindi",
        "_langListIndonesian": "Indonesiano",
        "_langListPortuguese": "Portoghese",
        "_langListRussian": "Russo",
        "_langListPolish": "Polacco",
        "_langListVietnamese": "Vietnamita",
        "_langListTurkish": "Turco",
        "_langListItalian": "Italiano",
        "_langListFarsi": "Farsi",
        // Pantalla de settings
        "_settingsApp": "Impostazioni App",
        "_settingsLang": "Lingua App",
        "_settingsEditor": "Impostazioni Editor",
        "_settingsSave": "Salvataggio automatico",
        "_settingsTypo": "Tipografia",
        "_settingsTypoWarning": "Cambiare la tipografia ti riporterà alla schermata principale per caricare il nuovo font",
        "_settingsResetAll": "Reimposta tutto",
        "_settingsRemoveAll": "Elimina tutte le note",
        "_settingsRemoveAllWarning": "ATTENZIONE! Premendo il pulsante qui sotto eliminerai tutte le note salvate",
        "_settingsLineSpacing": "Interlinea",
        "_settingsLetterSpacing": "Spaziatura lettere",
        "_settingsWordSpacing": "Spaziatura parole",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "Impostazioni",
        "_noteInputPlaceholder": "Scrivi la tua nota...",
        "_toastNoteSaved": "Nota salvata",
        "_toastTypoSaved": "Tipografia salvata",
        "_toastAutoSave": "Salvato automaticamente",
        "_toastActivated": "Attivato",
        "_toastDeactivated": "Disattivato",
        "_toastAllNotesDeleted": "Tutte le note sono state eliminate",
        "_lockNoteTitle": "Inserisci codice PIN",
        "_lockInfo": "Questa nota è bloccata, inserisci il PIN per accedere",
        "_lockError": "PIN errato",
        "_toastLineSpacingUpdated": "Interlinea aggiornata",
        "_toastLetterSpacingUpdated": "Spaziatura lettere aggiornata",
        "_toastWordSpacingUpdated": "Spaziatura parole aggiornata",
        // Modal de updates
        "_updatesModalNews": "Novità",
        "_updatesModalV1_1": "Ora puoi evidenziare i tuoi testi! 🖌️",
        "_updatesModalV1_2": "Nuovo pennello aggiunto: Evidenziatore 🖍️",
        "_updatesModalV1_3": "Strumenti di disegno migliorati 🔧",
        "_updatesModalV1_4": "Personalizza il colore di ogni parola 🎨",
        "_updatesModalV1_5": "Modifica la spaziatura tra paragrafi, lettere e parole ↔️",
        "_updatesModalV1_6": "😊 Speriamo che ti piacciano le novità 😊"
    },
    fa: { // Header Home
        "_headerTitle": "یادداشت‌های من",
        "_headerDropdownOption1": "تغییر شبکه",
        "_headerDropdownOption2": "تنظیمات",
        // Header Note
        "_headerNoteTitleNew": "افزودن یادداشت",
        "_headerNoteTitleEdit": "ویرایش یادداشت",
        "_headerNoteDropdownOption1": "حالت ویرایش",
        "_headerNoteDropdownOption2": "حالت خواندن",
        "_headerNoteDropdownOption3": "حذف یادداشت",
        "_headerNoteDropdownOption4": "باز کردن قفل یادداشت",
        "_headerNoteDropdownOption5": "قفل کردن یادداشت",
        "_headerNoteDropdownOption6": "تنظیمات",
        "_headerNoteDropdownOption7": "افزودن به علاقه‌مندی‌ها",
        "_headerNoteDropdownOption8": "حذف از علاقه‌مندی‌ها",
        // Home
        "_homeButton": "افزودن یادداشت",
        "_homeEmptyList": "شما هیچ یادداشتی ندارید",
        "_elementsSelected": "موارد انتخاب‌شده",
        // Lista de idiomas
        "_langListSpanish": "اسپانیایی",
        "_langListEnglish": "انگلیسی",
        "_langListArabic": "عربی",
        "_langListGerman": "آلمانی",
        "_langListFrench": "فرانسوی",
        "_langListHindi": "هندی",
        "_langListIndonesian": "اندونزیایی",
        "_langListPortuguese": "پرتغالی",
        "_langListRussian": "روسی",
        "_langListPolish": "لهستانی",
        "_langListVietnamese": "ویتنامی",
        "_langListTurkish": "ترکی",
        "_langListItalian": "ایتالیایی",
        "_langListFarsi": "فارسی",
        // Pantalla de settings
        "_settingsApp": "تنظیمات برنامه",
        "_settingsLang": "زبان برنامه",
        "_settingsEditor": "تنظیمات ویرایشگر",
        "_settingsSave": "ذخیره خودکار",
        "_settingsTypo": "تایپوگرافی",
        "_settingsTypoWarning": "تغییر تایپوگرافی شما را به صفحه اصلی می‌برد تا فونت جدید بارگذاری شود",
        "_settingsResetAll": "بازنشانی همه",
        "_settingsRemoveAll": "حذف همه یادداشت‌ها",
        "_settingsRemoveAllWarning": "هشدار! فشردن دکمه زیر تمام یادداشت‌های ذخیره‌شده را حذف می‌کند",
        "_settingsLineSpacing": "فاصله خطوط",
        "_settingsLetterSpacing": "فاصله حروف",
        "_settingsWordSpacing": "فاصله کلمات",
        // 05-09-2025: Faltaban las siguientes variables por traducir
        "_settingTitle": "تنظیمات",
        "_noteInputPlaceholder": "یادداشت خود را بنویسید...",
        "_toastNoteSaved": "یادداشت ذخیره شد",
        "_toastTypoSaved": "تایپوگرافی ذخیره شد",
        "_toastAutoSave": "به صورت خودکار ذخیره شد",
        "_toastActivated": "فعال شد",
        "_toastDeactivated": "غیرفعال شد",
        "_toastAllNotesDeleted": "همه یادداشت‌ها حذف شدند",
        "_lockNoteTitle": "کد PIN را وارد کنید",
        "_lockInfo": "این یادداشت قفل است، برای دسترسی کد PIN را وارد کنید",
        "_lockError": "کد PIN نادرست است",
        "_toastLineSpacingUpdated": "فاصله خطوط در یادداشت‌ها به‌روزرسانی شد",
        "_toastLetterSpacingUpdated": "فاصله حروف در یادداشت‌ها به‌روزرسانی شد",
        "_toastWordSpacingUpdated": "فاصله کلمات در یادداشت‌ها به‌روزرسانی شد",
        // Modal de updates
        "_updatesModalNews": "اخبار",
        "_updatesModalV1_1": "اکنون می‌توانید متون خود را برجسته کنید! 🖌️",
        "_updatesModalV1_2": "قلم جدید اضافه شد: هایلایتر 🖍️",
        "_updatesModalV1_3": "ابزارهای طراحی بهبود یافت 🔧",
        "_updatesModalV1_4": "رنگ هر کلمه را سفارشی کنید 🎨",
        "_updatesModalV1_5": "فاصله پاراگراف‌ها، حروف و کلمات را ویرایش کنید ↔️",
        "_updatesModalV1_6": "😊 امیدواریم از ویژگی‌های جدید لذت ببرید 😊"
    }
}

export { translations };