import AsyncStorage from "@react-native-async-storage/async-storage";
import uuid from 'react-native-uuid';
import { storage } from "./storage";
import { addNote } from "./sqlite";

export async function setInitialNote(language) {
    const value = await AsyncStorage.getItem(storage.FIRST_LAUNCH_APP);
    if (!value) {
        const id = uuid.v4();

        let content = "";

        switch (language) {
            case "es":
                content = `<div style="text-align: center;"><br></div><div style="text-align: center;"><span style="font-size: xx-large;">Te damos la bienvenida a Notas Coquette&nbsp;</span></div><div style="text-align: center;"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"></div><div style="text-align: center;"><font size="5">Disfruta de tus notas más bonitas y editalas a tu gusto 🥰</font></div><div style="text-a lign: center;"><ul><li style="text-align: left;"><b style=""><font size="4">Negritas</font></b></li><li style="text-align: left
;"><font size="4" style=""><i>Cursivas</i></font></li><li style="text-align: left;"><font size="4" style=""><u style="">Subrayado</u></font></li><li style="text-align: left;"><b><font size="4">Alinear</font></b></li><li style="text-align: left;"><b><font size="4">Listas</font></b></li><li style="text-align: left;"><font size="5" style="">Cambiar tamaño del texto</font></li><li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Separadores ⋇⋆✦⋆⋇</font></b></li><li style="text-align: left;"><font size="4" style="">Stickers</font></li><li style="text-align: left;"><font size="4" style=""><b>Deshacer y rehacer </b>cambios</font></li><li style="text-align: left;"><font size="4" 
style="">Cambia de <b>color</b></font></li><li style="text-align: left;"><font size="4" style=""><b>Dibuja </b>en tus notas</font></li><li style="text-align: left;"><font size="4" style="">Protege tus<b> notas con contraseña&nbsp;</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li></ul><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div></div>`;
                break;
            case "ar":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">نرحب بك في Notas Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">استمتع بأجمل ملاحظاتك وقم بتعديلها كما تحب 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">عريض</font></b></li> <li style="text-align: left;"><font size="4"><i>مائل</i></font></li> <li style="text-align: left;"><font size="4"><u>تحته خط</u></font></li> <li style="text-align: left;"><b><font size="4">محاذاة</font></b></li> <li style="text-align: left;"><b><font size="4">قوائم</font></b></li> <li style="text-align: left;"><font size="5">تغيير حجم النص</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ فواصل ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">ملصقات</font></li> <li style="text-align: left;"><font size="4"><b>تراجع وإعادة </b>التغييرات</font></li> <li style="text-align: left;"><font size="4">تغيير <b>اللون</b></font></li> <li style="text-align: left;"><font size="4"><b>ارسم </b>على ملاحظاتك</font></li> <li style="text-align: left;"><font size="4">احمِ <b>ملاحظاتك بكلمة مرور</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "de":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Willkommen bei Coquette Notes</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Genieße deine schönsten Notizen und bearbeite sie nach deinem Geschmack 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Fett</font></b></li> <li style="text-align: left;"><font size="4"><i>Kursiv</i></font></li> <li style="text-align: left;"><font size="4"><u>Unterstrichen</u></font></li> <li style="text-align: left;"><b><font size="4">Ausrichten</font></b></li> <li style="text-align: left;"><b><font size="4">Listen</font></b></li> <li style="text-align: left;"><font size="5">Textgröße ändern</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Trenner ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Sticker</font></li> <li style="text-align: left;"><font size="4"><b>Rückgängig machen und wiederherstellen</b></font></li> <li style="text-align: left;"><font size="4"><b>Farbe </b>ändern</font></li> <li style="text-align: left;"><font size="4"><b>Zeichne </b>auf deinen Notizen</font></li> <li style="text-align: left;"><font size="4">Schütze deine <b>Notizen mit Passwort</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "en":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Welcome to Coquette Notes</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Enjoy your cutest notes and edit them your way 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Bold</font></b></li> <li style="text-align: left;"><font size="4"><i>Italic</i></font></li> <li style="text-align: left;"><font size="4"><u>Underline</u></font></li> <li style="text-align: left;"><b><font size="4">Align</font></b></li> <li style="text-align: left;"><b><font size="4">Lists</font></b></li> <li style="text-align: left;"><font size="5">Change text size</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Separators ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Stickers</font></li> <li style="text-align: left;"><font size="4"><b>Undo and redo </b>changes</font></li> <li style="text-align: left;"><font size="4">Change <b>color</b></font></li> <li style="text-align: left;"><font size="4"><b>Draw </b>on your notes</font></li> <li style="text-align: left;"><font size="4">Protect your <b>notes with password</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "fr":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Bienvenue dans Bloc-notes Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Profite de tes plus jolies notes et personnalise-les comme tu veux 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Gras</font></b></li> <li style="text-align: left;"><font size="4"><i>Italique</i></font></li> <li style="text-align: left;"><font size="4"><u>Souligné</u></font></li> <li style="text-align: left;"><b><font size="4">Alignement</font></b></li> <li style="text-align: left;"><b><font size="4">Listes</font></b></li> <li style="text-align: left;"><font size="5">Changer la taille du texte</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Séparateurs ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Autocollants</font></li> <li style="text-align: left;"><font size="4"><b>Annuler et rétablir</b> les modifications</font></li> <li style="text-align: left;"><font size="4">Changer la <b>couleur</b></font></li> <li style="text-align: left;"><font size="4"><b>Dessine </b>sur tes notes</font></li> <li style="text-align: left;"><font size="4">Protège tes <b>notes avec un mot de passe</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "hi":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">नोट्स Coquette में आपका स्वागत है</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">अपना सबसे प्यारा नोट्स अनुभव करें और जैसा चाहें वैसा संपादित करें 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">बोल्ड</font></b></li> <li style="text-align: left;"><font size="4"><i>इटालिक</i></font></li> <li style="text-align: left;"><font size="4"><u>रेखांकित</u></font></li> <li style="text-align: left;"><b><font size="4">पंक्तिबद्ध</font></b></li> <li style="text-align: left;"><b><font size="4">सूचियाँ</font></b></li> <li style="text-align: left;"><font size="5">टेक्स्ट का आकार बदलें</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ विभाजक ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">स्टिकर</font></li> <li style="text-align: left;"><font size="4"><b>पूर्ववत और फिर से करें </b>बदलाव</font></li> <li style="text-align: left;"><font size="4"><b>रंग </b>बदलें</font></li> <li style="text-align: left;"><font size="4"><b>अपनी नोट्स पर </b>ड्रॉ करें</font></li> <li style="text-align: left;"><font size="4"><b>पासवर्ड</b> के साथ अपनी <b>नोट्स सुरक्षित रखें</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "id":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Selamat datang di Catatan Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Nikmati catatan paling lucu dan edit sesukamu 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Tebal</font></b></li> <li style="text-align: left;"><font size="4"><i>Miring</i></font></li> <li style="text-align: left;"><font size="4"><u>Garis bawah</u></font></li> <li style="text-align: left;"><b><font size="4">Rata teks</font></b></li> <li style="text-align: left;"><b><font size="4">Daftar</font></b></li> <li style="text-align: left;"><font size="5">Ubah ukuran teks</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Pemisah ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Stiker</font></li> <li style="text-align: left;"><font size="4"><b>Batalkan dan ulangi </b>perubahan</font></li> <li style="text-align: left;"><font size="4"><b>Ubah </b>warna</font></li> <li style="text-align: left;"><font size="4"><b>Gambar </b>di catatanmu</font></li> <li style="text-align: left;"><font size="4">Lindungi <b>catatanmu dengan kata sandi</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "pl":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Witamy w Notatkach Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Ciesz się uroczymi notatkami i edytuj je jak chcesz 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Pogrubienie</font></b></li> <li style="text-align: left;"><font size="4"><i>Kursywa</i></font></li> <li style="text-align: left;"><font size="4"><u>Podkreślenie</u></font></li> <li style="text-align: left;"><b><font size="4">Wyrównanie</font></b></li> <li style="text-align: left;"><b><font size="4">Listy</font></b></li> <li style="text-align: left;"><font size="5">Zmień rozmiar tekstu</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Separatory ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Naklejki</font></li> <li style="text-align: left;"><font size="4"><b>Cofnij i ponów</b> zmiany</font></li> <li style="text-align: left;"><font size="4"><b>Zmień </b>kolor</font></li> <li style="text-align: left;"><font size="4"><b>Rysuj </b>na swoich notatkach</font></li> <li style="text-align: left;"><font size="4">Chroń <b>swoje notatki hasłem</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "pt":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Bem-vinda ao Bloco de Notas Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Aproveite suas anotações mais fofas e edite como quiser 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Negrito</font></b></li> <li style="text-align: left;"><font size="4"><i>Itálico</i></font></li> <li style="text-align: left;"><font size="4"><u>Sublinhado</u></font></li> <li style="text-align: left;"><b><font size="4">Alinhamento</font></b></li> <li style="text-align: left;"><b><font size="4">Listas</font></b></li> <li style="text-align: left;"><font size="5">Alterar tamanho do texto</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Separadores ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Figurinhas</font></li> <li style="text-align: left;"><font size="4"><b>Desfazer e refazer</b> alterações</font></li> <li style="text-align: left;"><font size="4"><b>Mudar </b>cor</font></li> <li style="text-align: left;"><font size="4"><b>Desenhar </b>nas suas notas</font></li> <li style="text-align: left;"><font size="4">Proteja suas <b>notas com senha</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "ru":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Добро пожаловать в Заметки Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Наслаждайся самыми милыми заметками и редактируй их как хочешь 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Жирный</font></b></li> <li style="text-align: left;"><font size="4"><i>Курсив</i></font></li> <li style="text-align: left;"><font size="4"><u>Подчёркнутый</u></font></li> <li style="text-align: left;"><b><font size="4">Выравнивание</font></b></li> <li style="text-align: left;"><b><font size="4">Списки</font></b></li> <li style="text-align: left;"><font size="5">Изменить размер текста</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Разделители ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Стикеры</font></li> <li style="text-align: left;"><font size="4"><b>Отменить и повторить</b> изменения</font></li> <li style="text-align: left;"><font size="4"><b>Изменить </b>цвет</font></li> <li style="text-align: left;"><font size="4"><b>Рисуй </b>на своих заметках</font></li> <li style="text-align: left;"><font size="4">Защити <b>заметки паролем</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "tr":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Coquette Not Defteri'ne Hoş Geldin</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">En sevimli notların tadını çıkar ve istediğin gibi düzenle 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">Kalın</font></b></li> <li style="text-align: left;"><font size="4"><i>İtalik</i></font></li> <li style="text-align: left;"><font size="4"><u>Altı çizili</u></font></li> <li style="text-align: left;"><b><font size="4">Hizalama</font></b></li> <li style="text-align: left;"><b><font size="4">Listeler</font></b></li> <li style="text-align: left;"><font size="5">Metin boyutunu değiştir</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Ayraçlar ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Çıkartmalar</font></li> <li style="text-align: left;"><font size="4"><b>Geri al ve yinele</b></font></li> <li style="text-align: left;"><font size="4"><b>Renk </b>değiştir</font></li> <li style="text-align: left;"><font size="4"><b>Notlara </b>çizim yap</font></li> <li style="text-align: left;"><font size="4"><b>Notlarını şifreyle</b> koru</font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            case "vi":
                content = `<div style="text-align: center;"><br></div> <div style="text-align: center;"><span style="font-size: xx-large;">Chào mừng đến với Ghi chú Coquette</span></div> <div style="text-align: center;"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> <img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"> </div> <div style="text-align: center;"><font size="5">Tận hưởng những ghi chú đáng yêu nhất và chỉnh sửa theo ý thích 🥰</font></div> <div style="text-align: center;"> <ul> <li style="text-align: left;"><b><font size="4">In đậm</font></b></li> <li style="text-align: left;"><font size="4"><i>In nghiêng</i></font></li> <li style="text-align: left;"><font size="4"><u>Gạch chân</u></font></li> <li style="text-align: left;"><b><font size="4">Căn chỉnh</font></b></li> <li style="text-align: left;"><b><font size="4">Danh sách</font></b></li> <li style="text-align: left;"><font size="5">Thay đổi kích thước chữ</font></li> <li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Dấu phân cách ⋇⋆✦⋆⋇</font></b></li> <li style="text-align: left;"><font size="4">Hình dán</font></li> <li style="text-align: left;"><font size="4"><b>Hoàn tác và làm lại</b> thay đổi</font></li> <li style="text-align: left;"><font size="4"><b>Đổi </b>màu sắc</font></li> <li style="text-align: left;"><font size="4"><b>Vẽ </b>trên ghi chú</font></li> <li style="text-align: left;"><font size="4"><b>Bảo vệ ghi chú bằng mật khẩu</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li> </ul> </div>`
                break;
            default:
                content = `<div style="text-align: center;"><br></div><div style="text-align: center;"><span style="font-size: xx-large;">Te damos la bienvenida a Notas Coquette&nbsp;</span></div><div style="text-align: center;"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/banner.png"></div><div style="text-align: center;"><font size="5">Disfruta de tus notas más bonitas y editalas a tu gusto 🥰</font></div><div style="text-a lign: center;"><ul><li style="text-align: left;"><b style=""><font size="4">Negritas</font></b></li><li style="text-align: left
;"><font size="4" style=""><i>Cursivas</i></font></li><li style="text-align: left;"><font size="4" style=""><u style="">Subrayado</u></font></li><li style="text-align: left;"><b><font size="4">Alinear</font></b></li><li style="text-align: left;"><b><font size="4">Listas</font></b></li><li style="text-align: left;"><font size="5" style="">Cambiar tamaño del texto</font></li><li style="text-align: left;"><b><font size="4">⋇⋆✦⋆⋇ Separadores ⋇⋆✦⋆⋇</font></b></li><li style="text-align: left;"><font size="4" style="">Stickers</font></li><li style="text-align: left;"><font size="4" style=""><b>Deshacer y rehacer </b>cambios</font></li><li style="text-align: left;"><font size="4" 
style="">Cambia de <b>color</b></font></li><li style="text-align: left;"><font size="4" style=""><b>Dibuja </b>en tus notas</font></li><li style="text-align: left;"><font size="4" style="">Protege tus<b> notas con contraseña&nbsp;</b></font><img src="https://mollydigital.manu-scholz.com/wp-content/uploads/2025/07/lock.png"></li></ul><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div><div style="text-align: left;"><font size="4"><b><br></b></font></div></div>`;
        }

        const newNote = {
            id: id,
            content: content,
            date: new Date().getTime(),
            pwd: null
        }

        await addNote(id, newNote.content, newNote.pwd, newNote.date)
        await AsyncStorage.setItem(storage.FIRST_LAUNCH_APP, "true");
    }
}